# Generated by Django 3.2.3 on 2021-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210519_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(max_length=1000, null=True, verbose_name='설명'),
        ),
    ]
