# Generated by Django 3.2.2 on 2021-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.TextField(null=True, verbose_name='설명'),
        ),
    ]
